"""Discover code concepts that have no ontology entry yet.

Walks the public concept surface — classes deriving from the base classes
named in ``symbols.base_classes`` (``kb.yaml``) — subtracts everything any
ontology entry already mentions in ``implements:``/``underlying:``/
``related_symbols:``, and proposes stub ontology entries for what's left.

Stubs intentionally carry only the binding and whatever ``@brief`` the
header doxygen offers — the prose body and related-concepts edges are for
a human reviewer to fill in. The point is to make "this concept exists in
the code and nobody has written it down" a visible, auto-detected gap, not
to silently auto-populate the ontology with low-quality entries.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable, Sequence

from kb.config import get_config, get_settings
from kb.parsing.cpp import CppSymbol, parse_header
from kb.verify import _ontology_entries, resolve_symbol_roots


_PASCAL_SPLIT = re.compile(r"(?<=[a-z])(?=[A-Z])|(?<=[A-Z])(?=[A-Z][a-z])")
_DOXY_BRIEF = re.compile(r"@brief\s+(.+?)(?:\n|$)")


@dataclass
class StubProposal:
    qualified_name: str
    title: str
    slug: str
    brief: str
    header_path: str
    target_path: str  # ontology file path that would be created
    kind: str = "concept"

    def to_markdown(self) -> str:
        brief_block = self.brief or "*(no @brief in header; describe the concept here)*"
        return (
            "---\n"
            f"concept: {self.slug}\n"
            f"title: {self.title}\n"
            f"kind: {self.kind}\n"
            "implements:\n"
            f"  - {self.qualified_name}\n"
            "---\n"
            "\n"
            f"{brief_block}\n"
            "\n"
            "_Stub generated by `kb suggest-new` from the code headers. "
            "Add prose, `related_concepts:`, and any related symbols before merging._\n"
        )


def _strip_suffix(name: str, suffixes: Sequence[str]) -> str:
    for suffix in suffixes:
        if name.endswith(suffix) and name != suffix:
            return name[: -len(suffix)]
    return name


def _humanise(name: str, suffixes: Sequence[str] = ()) -> str:
    stripped = _strip_suffix(name, suffixes)
    parts = _PASCAL_SPLIT.split(stripped)
    return " ".join(p for p in parts if p)


def _slugify(name: str, suffixes: Sequence[str] = ()) -> str:
    stripped = _strip_suffix(name, suffixes)
    parts = _PASCAL_SPLIT.split(stripped)
    return "-".join(p.lower() for p in parts if p)


def _extract_brief(doxygen: str) -> str:
    if not doxygen:
        return ""
    m = _DOXY_BRIEF.search(doxygen)
    if m:
        return m.group(1).strip()
    # Some headers describe in plain prose without `@brief`. Take the first
    # non-empty line as a fallback.
    for line in doxygen.splitlines():
        line = line.strip()
        if line and not line.startswith("@"):
            return line
    return ""


def _covered_symbols(ontology_root: Path) -> set[str]:
    covered: set[str] = set()
    for _, meta in _ontology_entries(ontology_root):
        for field in ("implements", "underlying", "related_symbols"):
            for sym in meta.get(field) or []:
                covered.add(str(sym))
    return covered


def _concept_classes(
    include_root: Path, repo_root: Path, base_classes: Sequence[str]
) -> Iterable[CppSymbol]:
    markers = [f"public {base}" for base in base_classes]
    for hpp in include_root.rglob("*.hpp"):
        for sym in parse_header(hpp, repo_root):
            if sym.kind != "class":
                continue
            # Discriminate concept subclasses by base clause in the signature.
            # The parser stores the line up to ``{``, which for a technique
            # header looks like "class FishTechnique : public Technique" —
            # exactly what we need.
            if not any(marker in sym.signature for marker in markers):
                continue
            yield sym


def _symbols_config():
    try:
        return get_config().symbols
    except Exception:
        return None


def discover_uncovered(
    *,
    include_root: Path | None = None,
    ontology_root: Path | None = None,
    repo_root: Path | None = None,
    base_classes: Sequence[str] | None = None,
    strip_suffixes: Sequence[str] | None = None,
    stub_subdir: str | None = None,
    stub_kind: str | None = None,
) -> list[StubProposal]:
    sym_cfg = _symbols_config()
    if base_classes is None:
        base_classes = list(sym_cfg.base_classes) if sym_cfg else []
    if strip_suffixes is None:
        strip_suffixes = list(sym_cfg.strip_suffixes) if sym_cfg else []
    if stub_subdir is None:
        stub_subdir = sym_cfg.stub_subdir if sym_cfg else "concepts"
    if stub_kind is None:
        stub_kind = sym_cfg.stub_kind if sym_cfg else "concept"
    if not base_classes:
        raise ValueError(
            "No base classes to discover against — set symbols.base_classes in "
            "kb.yaml (e.g. [Technique]) or pass base_classes explicitly."
        )

    repo_root, ontology_root, include_root = resolve_symbol_roots(
        ontology_root=ontology_root, include_root=include_root, repo_root=repo_root
    )

    covered = _covered_symbols(ontology_root)
    proposals: list[StubProposal] = []
    for sym in _concept_classes(include_root, repo_root, base_classes):
        if sym.qualified_name in covered:
            continue
        title = _humanise(sym.name, strip_suffixes)
        slug = _slugify(sym.name, strip_suffixes)
        target = ontology_root / stub_subdir / f"{slug}.md"
        target_path = (
            str(target.relative_to(repo_root))
            if _is_under(target, repo_root)
            else str(target)
        )
        proposals.append(
            StubProposal(
                qualified_name=sym.qualified_name,
                title=title,
                slug=slug,
                brief=_extract_brief(sym.doxygen),
                header_path=sym.header_rel_path,
                target_path=target_path,
                kind=stub_kind,
            )
        )
    # De-duplicate (template aliases can share a qualified name path)
    seen: set[str] = set()
    unique: list[StubProposal] = []
    for p in proposals:
        if p.qualified_name in seen:
            continue
        seen.add(p.qualified_name)
        unique.append(p)
    unique.sort(key=lambda p: p.qualified_name)
    return unique


def apply_stubs(proposals: list[StubProposal], *, repo_root: Path | None = None) -> list[Path]:
    s = get_settings()
    repo_root = repo_root or s.repo_root
    written: list[Path] = []
    for p in proposals:
        target = Path(p.target_path)
        if not target.is_absolute():
            target = repo_root / target
        if target.exists():
            continue  # never overwrite — a human may have started this entry
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(p.to_markdown(), encoding="utf-8")
        written.append(target)
    return written


def _is_under(p: Path, root: Path) -> bool:
    try:
        p.resolve().relative_to(root.resolve())
        return True
    except ValueError:
        return False
